apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260531-155130-ccmv0n3sn3pi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260531-155130-ccmv0n3sn3pi.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260531-155130-ccmv0n3sn3pi-service
            port:
              number: 80
