apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260531-155130-ccmv0n3sn3pi-service
spec:
  selector:
    app: enterprise-system-20260531-155130-ccmv0n3sn3pi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
